### ISSUE TITLE
what toolchain name and version you using for this kernel?

### ISSUE THREAD

**Issue by rofikkerneldev** [HighwayStar/android_kernel_nubia_msm8953#1]
what toolchain name and version you using for this kernel?

i am used toolchain gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu failed to build default lineageos config
thank for bring kernel to nubia m2 

, and if you have free time to reply me in here or email rsoft3d@gmail.com

**Comment by rofikkerneldev** [comment]
![Screenshot_53](https://user-images.githubusercontent.com/26862653/80551438-a9f6ce00-89ed-11ea-9281-dc070c3b3033.png)

**Comment by HighwayStar** [comment]
I used gcc toolchain that shipped with AOSP/Lineage

**Comment by HighwayStar** [comment]
Your error looks like something wrong with PATH or missing binaries

**Comment by rofikkerneldev** [comment]
Thank you problem solved ,i forget add - in path to gcc
